// Bitmap fonts generated by tools/make_font.py: 4-bit coverage, two pixels per byte.
#pragma once
#include <stdint.h>

struct Glyph {
  uint32_t cp;
  uint32_t offset;
  uint8_t w, h;
  int8_t x, y;  // bearing from the pen position and the top of the line
  uint8_t adv;
};

struct Font {
  const Glyph* glyphs;
  int count;
  const uint8_t* bitmap;
  int lineHeight;
  int ascent;
};
