#!/usr/bin/env python3
"""Rasterise a TTF into a 4-bit anti-aliased bitmap font header for the pal firmware.

    python3 tools/make_font.py /usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf 26 caption > main/font_caption.h
    python3 tools/make_font.py /usr/share/fonts/truetype/ubuntu/Ubuntu-M.ttf 64 big "0123456789 -" > main/font_big.h
"""
import sys
from PIL import Image, ImageDraw, ImageFont

path, size, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
if len(sys.argv) > 4:
    chars = sys.argv[4]
else:
    chars = "".join(chr(c) for c in range(32, 127))
    chars += "".join(chr(c) for c in range(0xA0, 0x100))
    chars += "‘’“”…–—•·€™"
font = ImageFont.truetype(path, size)
ascent, descent = font.getmetrics()
codes = sorted(set(ord(c) for c in chars))

bitmap = bytearray()
glyphs = []
for cp in codes:
    ch = chr(cp)
    adv = round(font.getlength(ch))
    box = font.getbbox(ch)  # relative to the drawing origin (top of ascent)
    w, h = max(0, box[2] - box[0]), max(0, box[3] - box[1])
    offset = len(bitmap)
    if w and h:
        img = Image.new("L", (w, h), 0)
        ImageDraw.Draw(img).text((-box[0], -box[1]), ch, font=font, fill=255)
        px = img.load()
        for y in range(h):
            row = [px[x, y] >> 4 for x in range(w)]
            if len(row) % 2:
                row.append(0)
            for i in range(0, len(row), 2):
                bitmap.append(row[i] << 4 | row[i + 1])
    glyphs.append((cp, offset, w, h, box[0], box[1], adv))

N = name.upper()
print(f"// Generated by tools/make_font.py from {path.split('/')[-1]} at {size}px. Do not edit.")
print("#pragma once")
print('#include "font.h"')
print(f"static const uint8_t {name}_bitmap[] = {{")
for i in range(0, len(bitmap), 24):
    print("  " + ",".join(str(b) for b in bitmap[i : i + 24]) + ",")
print("};")
print(f"static const Glyph {name}_glyphs[] = {{")
for g in glyphs:
    print("  {%d, %d, %d, %d, %d, %d, %d}," % g)
print("};")
print(
    f"static const Font FONT_{N} = {{{name}_glyphs, {len(glyphs)}, {name}_bitmap, {ascent + descent}, {ascent}}};"
)
